### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by svapreddy** [heilhead/es-identifier-highlight#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.2
**Thrown From**: [es-identifier-highlight](https://github.com/heilhead/es-identifier-highlight) package, v0.2.5
### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1325

TypeError: Cannot read property 'getBufferPosition' of undefined
    at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1325:34)
    at View._highlightOccurrences (/Users/svpr/.atom/packages/es-identifier-highlight/lib/view.js:179:36)
    at complete (/Users/svpr/.atom/packages/es-identifier-highlight/node_modules/lodash.debounce/index.js:142:21)
    at delayed (/Users/svpr/.atom/packages/es-identifier-highlight/node_modules/lodash.debounce/index.js:152:7)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "github-web"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
autoclose-html, v0.18.0
autocomplete-erlang, v1.1.1
autocomplete-html-entities, v0.1.0
browser-plus, v0.0.34
docblockr, v0.7.3
es-identifier-highlight, v0.2.5
git-log, v0.4.1
github-web, v1.1.0
grunt-runner, v0.11.0
language-elixir, v0.5.2
language-erlang, v3.0.0
language-nim, v0.2.2
language-swift, v0.4.0
line-diff-details, v1.1.2
linter-swiftc, v2.0.0
minimap, v4.12.3
my-github-profile, v0.2.1
pigments, v0.11.0
run-in-browser, v0.1.3
seti-ui, v0.8.0
travis-ci-status, v0.16.0
tree-view-filter, v0.3.7

# Dev
No dev packages
```

**Comment by heilhead** [comment]
I was able to reproduce the bug and will fix it in the next version (probably tomorrow).

Thanks for reporting!
