### ISSUE TITLE
'Failed to activate the es-identifier-highlight package' on startup

### ISSUE THREAD

**Issue by benturner** [heilhead/es-identifier-highlight#13]
A recent update is causing this to be thrown every time I launch Atom with a previous js file:
```
TypeError: visitor[(override || node.type)] is not a function
    at c (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at Object.ExportNamedDeclaration (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/inspector.js:149:21)
    at c (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at /Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/inspector.js:101:48
    at Array.forEach (native)
    at Object.ScopeBody (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/inspector.js:101:31)
    at c (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at Object.Program (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/inspector.js:108:17)
    at c (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at recursive (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/walk.js:56:4)
    at Inspector._inspect (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/inspector.js:90:9)
    at Inspector.parse (/Users/bent/.atom/packages/es-identifier-highlight/lib/inspector/inspector.js:46:14)
    at View._handleSourceChange (/Users/bent/.atom/packages/es-identifier-highlight/lib/view.js:241:25)
    at View._handleEditorChange (/Users/bent/.atom/packages/es-identifier-highlight/lib/view.js:119:14)
    at new View (/Users/bent/.atom/packages/es-identifier-highlight/lib/view.js:59:14)
    at Object.activate (/Users/bent/.atom/packages/es-identifier-highlight/lib/bootstrap.js:20:22)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:779:28
```
Using Atom 1.11.2 and es-identifier-highlight 0.4.0

**Comment by vehas** [comment]
. + 1 ,  on 1.12.2 and es-identifier-highlight 0.4.0

**Comment by heilhead** [comment]
Can you show sample js sources that cause this error?

**Comment by heilhead** [comment]
Hey guys, I've found a bug with some spread syntax cases generating errors. Please check if it's fixed for you with 0.4.1 release.

**Comment by benturner** [comment]
I still see this on 0.4.1. It appears to be something to do with Flow type definitions (https://flowtype.org). This alone is sufficient to trigger the exception:

``` js
type Foo = string;
```

**Comment by heilhead** [comment]
Sorry, but Flow is not supported at the moment. It's definitely on my list (along with TS) but proper implementation would require some time.

I've pushed 0.4.3 release that fixes error messages when parsing Flow code, but the plugin still won't highlight anything.
