### ISSUE TITLE
Uncaught TypeError: visitor[(override || node.type)] is not a function

### ISSUE THREAD

**Issue by demonfchan** [heilhead/es-identifier-highlight#19]
[Enter steps to reproduce:]

1. type "import(1)" in any js file
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [es-identifier-highlight](https://github.com/heilhead/es-identifier-highlight) package 0.4.3

### Stack Trace

Uncaught TypeError: visitor[(override || node.type)] is not a function

```

TypeError: visitor[(override || node.type)] is not a function
    at /packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at Object.skipThrough (/packages/es-identifier-highlight/lib/inspector/walk.js:161:44)
    at /packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at Object.base.NewExpression.base.CallExpression (/packages/es-identifier-highlight/lib/inspector/walk.js:333:3)
    at /packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at Object.skipThrough (/packages/es-identifier-highlight/lib/inspector/walk.js:161:44)
    at /packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at Object.base.ExpressionStatement.base.ParenthesizedExpression (/packages/es-identifier-highlight/lib/inspector/walk.js:192:20)
    at /packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at /packages/es-identifier-highlight/lib/inspector/inspector.js:103:48
    at Array.forEach (native)
    at Object.ScopeBody (/packages/es-identifier-highlight/lib/inspector/inspector.js:103:31)
    at /packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at Object.Program (/packages/es-identifier-highlight/lib/inspector/inspector.js:110:17)
    at /packages/es-identifier-highlight/lib/inspector/walk.js:55:35)
    at recursive (/packages/es-identifier-highlight/lib/inspector/walk.js:56:4)
    at Inspector._inspect (/packages/es-identifier-highlight/lib/inspector/inspector.js:92:9)
    at Inspector.parse (/packages/es-identifier-highlight/lib/inspector/inspector.js:46:14)
    at View._handleSourceChange (/packages/es-identifier-highlight/lib/view.js:241:25)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:1371:25
```

### Commands

```
     -5:23.5.0 core:backspace (input.hidden-input)
     -5:22.7.0 core:save (input.hidden-input)
     -0:25.6.0 editor:newline (input.hidden-input)
     -0:21.7.0 core:move-left (input.hidden-input)
     -0:19.8.0 editor:consolidate-selections (input.hidden-input)
     -0:19.8.0 core:cancel (input.hidden-input)
  2x -0:19.1.0 core:move-left (input.hidden-input)
  3x -0:18.6.0 core:select-right (input.hidden-input)
  2x -0:17.6.0 core:backspace (input.hidden-input)
     -0:13.8.0 core:move-left (input.hidden-input)
     -0:12.8.0 core:move-right (input.hidden-input)
  3x -0:12.4.0 core:select-left (input.hidden-input)
     -0:11.4.0 core:backspace (input.hidden-input)
     -0:10.6.0 editor:select-to-first-character-of-line (input.hidden-input)
  3x -0:10.4.0 core:backspace (input.hidden-input)
     -0:08.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-modules 1.6.8 
es-identifier-highlight 0.4.3 
language-javascript-jsx 0.3.7 
```

**Comment by FlorianWendelborn** [comment]
~~@heilhead Do you need further information to fix this? I can reproduce this on the latest Atom with the latest `es-identifier-highlight`.~~

**Comment by suchipi** [comment]
I am also seeing this when using `export foo from "./foo"`

**Comment by rodneyrehm** [comment]
I'm getting this for `const foo = () => import('./foo')`

**Comment by FlorianWendelborn** [comment]
~~@rodneyrehm I'm quite sure that's a syntax error.~~

**Comment by vm06007** [comment]
any updates? I'm seeing this issue too! when is the fix coming?

**Comment by tvld** [comment]
Still here, after I write:
```js

const World = () => import('@/components/World')

```

**Comment by brettz9** [comment]
`import()` is a [proposal](https://github.com/tc39/proposal-dynamic-import) and is currently [working in Chrome](https://developers.google.com/web/updates/2017/11/dynamic-import) so this would be great to get fixed...

**Comment by brettz9** [comment]
~~I got rid of this problem with `npm i babel-eslint` and~~

~~adding in `.eslintrc`:~~

~~`"parser": "babel-eslint"`~~

**Comment by brettz9** [comment]
No, apologies, that just fixed the linting...

**Comment by tvld** [comment]
@dodekeract No, I would think that @rodneyrehm 's code is ok: approved code for code splitting and dynamic component loading. Dynamic imports are a stage-3 proposal; Babel should handle it.
