### ISSUE TITLE
Failed to parse source:  SyntaxError: Unexpected token (138:20)

### ISSUE THREAD

**Issue by osaier** [heilhead/es-identifier-highlight#4]
Hi,

Looks great but never highlighted anything for me since I installed it 3 days ago in Atom 1.0.19. The following error is consistently thrown to console : 

``` java
Failed to parse source:  SyntaxError: Unexpected token (138:20)
  at Parser.pp.raise (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn/dist/acorn.js:975:13)
  at Parser.pp.unexpected (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn/dist/acorn.js:1523:8)
  at Parser.pp.expect (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn/dist/acorn.js:1517:26)
  at Parser.pp.parseBindingList (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn/dist/acorn.js:1172:40)
  at Parser.pp.parseMethod (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn/dist/acorn.js:572:22)
  at Parser.pp.parsePropertyValue (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn/dist/acorn.js:516:23)
  at Parser.pp.parseObj (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn/dist/acorn.js:501:10)
  at Parser.pp.parseExprAtom (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn/dist/acorn.js:314:19)
  at Parser.parseExprAtom (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn-jsx/inject.js:367:24)
  at Parser.pp.parseExprSubscripts (/Users/olivier/.atom/packages/es-identifier-highlight/node_modules/acorn/dist/acorn.js:221:19)
```

**Comment by heilhead** [comment]
Hi. Can you give me a sample code so I'd be able to reproduce this?

**Comment by osaier** [comment]
Oh ok, types are causing this.

``` javascript
_renderPage(data) { ... } //ok
_renderPage(data: Object) { ... } //breaks highlighting
```

**Comment by heilhead** [comment]
Well, it's the same as in #2. I may implement it using acorn plugins, but don't have time for this now. Would appreciate if someone else makes a PR adding flow syntax and/or es7 extensions, but otherwise it will have to wait. Sorry.
